# General Jekyll Config
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlight: true
url: http://elasticsearch.kulekci.net
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]